### ISSUE TITLE
Implement CLI for getting (registering) a new atSign

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_java#1]
**Is your feature request related to a problem? Please describe.**
Currently there is an Onboard CLI for onboarding a new atSign, but it requires that you already know the atSign and its shared secret.

**Describe the solution you'd like**
Need a Register CLI which will grab a new atSign and its shared secret; this information can then be used by the Onboard CLI to generate keys etc

**Comment by gkc** [comment]
@srieteja are you interested in picking this up? (As I believe you implemented this for the Dart client)

**Comment by srieteja** [comment]
Yes, I am interested to work on this @gkc

**Comment by srieteja** [comment]
Implementation of Register CLI is functionally complete (one can get a free atsign and register it to their email). A minuscule task of storing the API key in the config file is remaining, which I am working on at the moment.

**Comment by srieteja** [comment]
Ready to merge into trunk
