### ISSUE TITLE
Update register_cli to match API changes in AtRegistrar

### ISSUE THREAD

**Issue by srieteja** [atsign-foundation/at_java#115]
### Describe the bug

- The registrar has modified some API calls, update the methods to match the current behaviour of the registrar.
- Update the code in RegisterUtil class according to the new Registrar API responses
- Update exception catching and user-messages

### Expected behavior

Register should be able to activate atsigns and display accurate user messages

### Process Checklist

- [x] Modify RegisterUtil methods with new Registrar API call responses
- [x] Update docs/readme

**Comment by srieteja** [comment]
Most of the implementation is done. Carrying this to the next sprint to test, update docs and get the pr merged

**Comment by cconstab** [comment]
Fyi this blocking the release of sshnp v3.1.0

So please let me know when pushed to pub.dev

**Comment by gkc** [comment]
Can I confirm please that this ticket refers to work in the at_java repo and therefore the description in this issue is wrong? There is a ticket in at_libraries for the Dart package work https://github.com/atsign-foundation/at_libraries/issues/330

**Comment by srieteja** [comment]
It does refer to the at_java repo. Some API calls have been modified in the registrar side, making changes accordingly in at_java's register_cli. This does not relate to fetching the cram using verification code, yet.

**Comment by gkc** [comment]
Please can you update the description and task list so it reflects the work for this repo - thank you! (This is me being very picky ... we don't have onboarding_cli or register_cli programs in this repo)

**Comment by srieteja** [comment]
> Please can you update the description and task list so it reflects the work for this repo - thank you!

My bad, the ticket had similar content to the at_libraries ticket. I am updating this ticket as we speak. I might be accidentally mixing class names from the dart onboarding_cli.
