### ISSUE TITLE
Scan CLI and AtClientImpl _getAtKeys implementation

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_java#21]
PR = #19 

There is a lot of hidden work behind `_getAtKeys` in `AtClientImpl` such as string parsing from `scan` and AtKey object instantiating via `KeyBuilders`.

**Comment by JeremyTubongbanua** [comment]
Key discussion (from Engineering Google Chat thread)
https://docs.google.com/document/d/1E-FIHySO73k036kaXnkuUESkOQ2PUOLex2t7fMovc4I/edit?usp=sharing

**Comment by JeremyTubongbanua** [comment]
#19

**Comment by JeremyTubongbanua** [comment]
@public API notes 

https://docs.google.com/document/d/1DaH23kW7gpPdFiTIWxScIovJXiGqJS9eNnRcs7m_wY0/edit#heading=h.53nl6rorpt9q

**Comment by gkc** [comment]
This is pretty much done pending PR reviews

**Comment by gkc** [comment]
About 5SP worth of work this sprint
