### ISSUE TITLE
Maven deploys failing

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_java#231]
### Describe the bug

For a little while now the Maven workflow has been failing:

```log
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.425 s
[INFO] Finished at: 2024-10-08T08:52:18Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project at_client: Exit code: 2 -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

### Steps to reproduce

1. First I merge a (Dependabot) PR
2. Then the ``Maven Deploy `at_client` to Nexus OSSRH`` workflow runs.
3. And then it fails, sending out an alert email.

### Expected behavior

Maven Deploy completes sucessfully

### Additional context

Logs from the last successful run aren't available any more

**Comment by JeremyTubongbanua** [comment]
![image](https://github.com/user-attachments/assets/0e4b8080-c7c2-4ce6-a4fa-b482d542c267)

The GPG key expired is the reason why

**Comment by JeremyTubongbanua** [comment]
I updated the secrets on my fork and got it to upload successfully by updating the secrets.

![image](https://github.com/user-attachments/assets/3c2f76d7-b571-4ddb-9e6b-fe3dde2c1266)

Here's a recent example

- [my fork](https://github.com/JeremyTubongbanua/at_java/actions/runs/11538379338)
- the uploaded [maven dependency](https://s01.oss.sonatype.org/#nexus-search;quick~atsign-foundation)

I submitted a [docs PR](https://github.com/atsign-foundation/at_java/pull/239) pending your review @cpswan to test if the maven deployment works after merging this PR to trunk

**Comment by JeremyTubongbanua** [comment]
Appears to be functional https://github.com/atsign-foundation/at_java/actions/runs/11540989736/job/32122449892
