### ISSUE TITLE
Enhance REPL so that some AtClient methods can be called interactively

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_java#4]
**Is your feature request related to a problem? Please describe.**
REPL is super-useful but currently just handles everything it's sent as an @ protocol command which it sends directly to the Secondary; this greatly limits its usefulness for interactive sharing of data, as the value needs to be encrypted before it is sent

**Describe the solution you'd like**
Enable share(..), get(..), put(..), delete(..) methods to be called from the REPL. At a minimum, support share(..) and get(..)

**Comment by JeremyTubongbanua** [comment]
I've already started on this

**Comment by JeremyTubongbanua** [comment]
I'd like to continue working on this

**Comment by gkc** [comment]
Thanks Jeremy. FYI I've added a very simple `get` and `put` into the REPL

**Comment by JeremyTubongbanua** [comment]
Okay I will continue on what you have built

#34

**Comment by JeremyTubongbanua** [comment]
Continuing in PR45

**Comment by JeremyTubongbanua** [comment]
@ksanty The code is done.. but the code is waiting to be merged. Should this move to the next sprint?
