### ISSUE TITLE
hacktoberfest java | camera stream byte[] utility

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_java#52]
## Premise

One of the things the atPlatform specializes in is sending end-to-end encrypted binary data. A huge application would be to send a camera stream through atSigns.

## What to do
Create a utility class to fetch the camera stream from a USB camera (or a camera from your choice) and convert it into a Map of images.
Perhaps start with taking a screenshot of the camera stream and converting that into a byte[] array.

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by kaggrwal** [comment]
@JeremyTubongbanua I have started working on this, can you please assign this to me ?

**Comment by gkc** [comment]
@kaggrwal Done - thank you!

**Comment by JeremyTubongbanua** [comment]
> @JeremyTubongbanua I have started working on this, can you please assign this to me ?

Thanks @kaggrwal 
Am eager to see how your solution turns out :) Your work for this issue will be a big plus to our repository

**Comment by kaggrwal** [comment]
@gkc @JeremyTubongbanua Glad to be part of atSign communtiy, i have provided the solution and pushed the changes in #59, please review and let me know if any improvement is required.
