### ISSUE TITLE
hacktoberfest java | File <-> byte[] utility

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_java#53]
## Premise

The atPlatform is perfect for sending end-to-end encrypted files. [atmospherePro](https://atsign.com/resources/articles/heres-why-you-want-to-send-all-your-files-with-mospherepro/) does this too, but is written in Dart. It would be great if we could do the same in Java.

## What needs to be done

A utility method that converts a File object into an array of bytes (byte[]).
Another method that converts the byte[] back to a File object would be great as well.

Something like:
```java
public static byte[] convert(File);
public static File convert(byte[]);
```

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by yashjain1974** [comment]
Hey! I wanted to code this method but I don't know in which java file you wanted to implement this method?

**Comment by VinaySheth** [comment]
Hi, I want to contribute to this issue, Can you please assign me.

**Comment by VinaySheth** [comment]
> Hi, I want to contribute to this issue, Can you please assign me.

Thank You @JeremyTubongbanua  for providing me the opportunity as this would be my first "technical/coding" contribution to the Hacktoberfest!
