### ISSUE TITLE
hacktoberfest java | image <-> byte[] utility

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_java#54]
## Premise

The atPlatform is perfect for sending data and files peer-to-peer. The atPlatform ensures that the data sent is only readable by the end user.

## What needs to be done

- Create 2 utility methods (one for converting an image to an array of bytes (byte[]) and another for converting the byte[] image to an image object)
- You can do this in anyway you like (does not have to be a method, could be an entire class! or multiple classes)
- Even codeblocks are appreciated

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by anmol-Git** [comment]
Hi,  I want to contribute to this issue, Can you please assign me.

**Comment by gkc** [comment]
@anmol-Git Done - thank you!

**Comment by anmol-Git** [comment]
@gkc thanks for assigning this issue

**Comment by VinaySheth** [comment]
Hi, I want to contribute to this issue, Can you please assign me.

**Comment by JeremyTubongbanua** [comment]
I take that back, I've been given word that we're allowing multiple people to work on the same issue. However, we will be taking the highest quality PR.

Thanks for your interest @VinaySheth am excited to see what you will do :)

**Comment by VinaySheth** [comment]
> I take that back, I've been given word that we're allowing multiple people to work on the same issue. However, we will be taking the highest quality PR.
> 
> Thanks for your interest @VinaySheth am excited to see what you will do :)

Thank You @JeremyTubongbanua for providing me the opportunity as this would be my first "technical/coding" contribution to the Hacktoberfest!
