### ISSUE TITLE
hacktoberfest java | String <-> byte[]

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_java#61]
## What needs to be done

- [ ] Create a class named `ByteUtil`
- [ ] Create a method `String convert(byte[] data)` that converts an array of bytes to a String
- [ ] Create another method `byte[] convert(String data)` that converts a String to an array of bytes
- [ ] Please comment on the GitHub issue to be assigned this task. 

## How to contribute

1. Create a fork of `at_java`
2. Make your contributions via `git add .` and `git commit -m "feat: new feature!"
3. Make a pull request to the trunk of this repository and make sure you add `closes #XYZissue` to the description so it will be related to this issue 

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

**Comment by sid172014** [comment]
Hey I would love to work on this , can you please assign me for this issue ?

**Comment by sid172014** [comment]
Hey i've made a pull request @JeremyTubongbanua can you please have a look?
