### ISSUE TITLE
Java PublicKey bypassCache

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_java#74]
## Background

In our Dart SDK, we provide an optional parameter `GetRequestOptions` for the developer to `bypassCache:true` when doing a `plookup:` (which does a fresh plookup as opposed to llooking up the local cached public key, if it exists).

```dart
// AtClient.get method
@override
Future<AtValue> get(AtKey atKey, {bool isDedicated = false, GetRequestOptions? getRequestOptions})
```

```dart
// GetRequestOptions class allows them to bypass cache when getting a PublicKey
/// Request params for at client get method
class GetRequestOptions extends RequestOptions {
  bool bypassCache = false;
}
```

## Problem

Java needs a way of doing a `plookup:bypassCache:true` as well. Should this be the approach?

Overload the `get(PublicKey)` method with some kind of arguments option
```java
public CompletableFuture<String> get(PublicKey publicKey, GetRequestOptions getRequestOptions) {
    // check if bypassCache, then do `bypassCache:true`
}
```

Usage would be similar to:

```java
// assume atClient and publicKey variables are non-null
atClient.get(publicKey, new GetRequestOptions().bypassCache(true).build());
```

**Comment by JeremyTubongbanua** [comment]
@gkc Is this a good approach for implementing `bypassCache:true` to the Java SDK?

**Comment by gkc** [comment]
Yep overloading the method is fine for this use case
