### ISSUE TITLE
Implement creation of self keys in Java SDK

### ISSUE THREAD

**Issue by VJag** [atsign-foundation/at_java#8]
Implement the ability to create the self keys in the Java SDK

**Comment by gkc** [comment]
Some progress in PR37 by @VJag

**Comment by gkc** [comment]
@JeremyTubongbanua You've completed this, correct?

**Comment by JeremyTubongbanua** [comment]
> @JeremyTubongbanua You've completed this, correct?

Yes in #29

**Comment by gkc** [comment]
Great job Jeremy, thank you!
